name: Upload Nuget Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          submodules: 'recursive'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Nuget
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages for service
        run: nuget restore projects/Mukaida.Nuget.sln

      # ビルド
      - name: Build with dotnet
        run: dotnet build projects/Mukaida.Nuget.sln --configuration Release

      # パッケージバージョンを取得
      #- name: Setup Version
      #  id: setup_version
      #  run: echo "grep -Po '(?<=<Version>)([^</Version>]*)' './projects/Mukaida.Nuget/Mukaida.Nuget.csproj'" >> $GITHUB_OUTPUT
      - name: Setup Version
        id: setup_version
        run: |
          #grep -Po '(?<=<Version>)([^</Version>]*)' './projects/Mukaida.Nuget/Mukaida.Nuget.csproj'
          echo "VERSION="$(grep -Po '(?<=<Version>)([^</Version>]*)' './projects/Mukaida.Nuget/Mukaida.Nuget.csproj') >> $GITHUB_OUTPUT

      - name: Echo Version
        run: echo ${{ steps.setup_version.outputs.VERSION }}
        
      - name: Pack NuGet Package
        run: dotnet pack Sharprompt/Sharprompt.csproj -c Release -o ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}

      - name: Publish
        run: dotnet nuget push dist/*.nupkg -k ${{ secrets.KENTEM_NUGET_KEY }} -s https://ksnuget-barget.azurewebsites.net/v3/index.json
